#pragma once

#define BIKE_MB_AI_WIFI_SSID "CHANGE_ME_WIFI_SSID"
#define BIKE_MB_AI_WIFI_PASSWORD "CHANGE_ME_WIFI_PASSWORD"
#define BIKE_MB_AI_STT_TOKEN "CHANGE_ME_STT_TOKEN"
#define BIKE_MB_AI_DEEPSEEK_TOKEN "CHANGE_ME_DEEPSEEK_TOKEN"
#define BIKE_MB_AI_TTS_TOKEN "CHANGE_ME_TTS_TOKEN"
#define BIKE_MB_AI_DEFAULT_STREAM_URL "https://example.invalid/audio.mp3"
