[platformio]
default_envs = esp32-s3-touch-lcd-1-85c
core_dir = ../../../.pio-home
build_dir = ../../build/pio-bikemb
libdeps_dir = ../../build/pio-libdeps

[env:esp32-s3-touch-lcd-1-85c]
platform = https://github.com/pioarduino/platform-espressif32.git#55.03.39
board = esp32-s3-devkitc1-n16r8
framework = arduino
board_build.flash_size = 16MB
board_build.f_cpu = 240000000L

upload_port = COM5
monitor_port = COM5
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time

lib_deps =
  lvgl/lvgl@^8.4.0

build_flags =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D CORE_DEBUG_LEVEL=3
  -D LV_CONF_INCLUDE_SIMPLE
  -I include

[env:esp32-s3-touch-lcd-1-85c-audio-self-test]
extends = env:esp32-s3-touch-lcd-1-85c
lib_deps =
lib_extra_dirs = ../../build/pio-libdeps/esp32-s3-touch-lcd-1-85c
build_flags =
  ${env:esp32-s3-touch-lcd-1-85c.build_flags}
  -D BIKE_MB_ENABLE_AUDIO_SELF_TEST=1

[env:esp32-s3-touch-lcd-1-85c-mode-prompts-test]
extends = env:esp32-s3-touch-lcd-1-85c
lib_deps =
lib_extra_dirs = ../../build/pio-libdeps/esp32-s3-touch-lcd-1-85c
build_flags =
  ${env:esp32-s3-touch-lcd-1-85c.build_flags}
  -D BIKE_MB_ENABLE_AUDIO_PROMPTS=1

[env:esp32-s3-touch-lcd-1-85c-voice-direct-test]
extends = env:esp32-s3-touch-lcd-1-85c
board_build.partitions = esp_sr_16.csv
extra_scripts = pre:../../../tools/pio_upload_srmodels.py
lib_deps =
lib_extra_dirs = ../../build/pio-libdeps/esp32-s3-touch-lcd-1-85c
build_flags =
  ${env:esp32-s3-touch-lcd-1-85c.build_flags}
  -D BIKE_MB_ENABLE_VOICE_COMMANDS=1

[env:esp32-s3-touch-lcd-1-85c-idf]
platform = https://github.com/pioarduino/platform-espressif32.git#55.03.39
board = esp32-s3-devkitc1-n16r8
framework = espidf
board_build.flash_size = 16MB
board_build.f_cpu = 240000000L
board_build.cmake_extra_args =
  -DSDKCONFIG=../../build/pio-bikemb/esp32-s3-touch-lcd-1-85c-idf/sdkconfig

upload_port = COM5
monitor_port = COM5
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time

lib_deps =
  lvgl/lvgl@^8.4.0

build_flags =
  -D LV_CONF_INCLUDE_SIMPLE
  -D BIKE_MB_USE_ESPIDF_RUNTIME=1
  -I include
